version: "3.5"
services:
  traefik:
    container_name: traefik
    build:
      context: traefik
    networks:
      - nymph-stack
    ports:
      - 127.0.0.1:13005:13005
      - 127.0.0.1:13006:13006
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

networks:
  nymph-stack:
    name: nymph-stack
    driver: bridge
